### ISSUE TITLE
Compile error with GNU and Intel

### ISSUE THREAD

**Issue by fccf** [szaghi/StringiFor#18]
Dear szaghi,

I would like to compile your very useful module `Stringifor` under Ubuntu17.04 wiht GNU gfortran6.3.0. But it fails with the following message:
```
src/lib/stringifor_string_t.F90:144:19:

     generic :: read(formatted) => read_formatted       !< Formatted input.
                   1
Error: Expected ‘=>’ at (1)
```
then I use Intel Fortran2016 to compile, it also occur errors:

```
src/lib/stringifor_string_t.F90(4120): warning #5268: Extension to standard: The text exceeds right hand column allowed on the line.
   character(len(iomsg))                    :: local_iomsg    !< Local variant of iomsg, so it doesn't get inappropriately redefined.
------------------------------------------------------------------------------------------------------------------------------------^
src/lib/stringifor_string_t.F90(3823): error #7508: A specification function must be a pure function.   [LEN]
   character(len=len(iomsg))                :: local_iomsg !< Local variant of iomsg, so it doesn't get inappropriately redefined.
-----------------^

```

Could you help me to resolve it?

Sincerely

FANGCHAO

**Comment by szaghi** [comment]
Dear @fccf 

thank you for your kind words.

For GNU the simple solution is to use a release before the last one: because GNU Fortran 7.x has now support for UDTIO I enabled it, but the prior 6.3.0 has not. You should be able to use version [0.9.5](https://github.com/szaghi/StringiFor/releases/tag/v0.9.5) with GNU gfortran 6.3.0. (however you could face with some issue with third party libraries, I am updating all my ZOO, in that case feel free to ask me further details, I'll guide you to download the correct version of all libraries).

For Intel issue I think there is not a simple solution, it sound more a bug of the compiler. I have not access to intel 16, I have only Intel 17 and 18beta and with both StringiFor works. I am sorry, but I am not helpful with Intel.

Let me know if you are successful to use StringiFor with GNU.

Cheers

**Comment by fccf** [comment]
Dear @szaghi 

Thanks for your help.

I compile this module successfully with GNU Fortran 7.1. 

I also cloned ZOO, and found it very interesting and useful.  but there are still some errors when compile it.

Cheers

**Comment by szaghi** [comment]
@fccf 

Yes, I have broken the ZOO in these days. I have started a general update, but it is not completed and for now some libraries have broken dependencies. Sorry for the inconvenience, but I am very busy.

Cheers

**Comment by fccf** [comment]
@szaghi 

Your work is very meaningful, Thank you.

Cheers
